# Generated by Django 3.2.7 on 2021-10-11 14:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snaps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_link',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
